name: Build Arch Linux Packages
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install base-devel and deps
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git libsodium dkms linux-headers libbpf cmake clang llvm

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Clone upstream repository
        run: git clone https://github.com/hrimfaxi/tutuicmptunnel.git tutuicmptunnel

      - name: Extract version from CMakeLists.txt
        id: version_step
        run: |
          VERSION=$(grep -i "project(tutuicmptunnel VERSION" tutuicmptunnel/CMakeLists.txt | sed -n 's/.*VERSION \([^ ]*\).*/\1/p')
          echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version extracted from CMake: ${VERSION}"

      - name: Prepare PKGBUILD
        run: |
          cp contrib/scripts/PKGBUILD .
          sed -i "s/^pkgver=.*/pkgver=${PACKAGE_VERSION}/" PKGBUILD
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

      - name: Build package
        run: |
          sudo -u builder bash -c "
            sudo chown -R builder:builder $GITHUB_WORKSPACE
            makepkg -sf --noconfirm
          "

      - name: Collect artifacts
        run: |
          mkdir -p output
          mv ./*.pkg.tar.zst output/

      - uses: actions/upload-artifact@v4
        with:
          name: tutuicmptunnel-archlinux-pkgs
          path: output/*.pkg.tar.zst
